#!/bin/bash

function has-session {
  tmux has-session -t 'FoodInsecurity'  2>/dev/null
}

if has-session
then
  tmux a -t 'FoodInsecurity'
else
  # main work directory:
  proj="/home/chaconmo/Documents/Projects/FoodSecurity/5.Studies/MapFoodInse/"
  # tmux new-session -d -c $proj"7.Writing/paper-spmirt" -s 'FoodInsecurity'
  tmux new-session -d -c $proj -s 'FoodInsecurity'
  # window: todo
  tmux rename-window "Todo"
  tmux send-keys \
    'nvim ~/Documents/Nvim/Vimwiki/Food\ Insecurity\ Study\ Todo.wiki' C-m
  # window: notes
  tmux new-window
  tmux rename-window "Notes"
  tmux send-keys \
    'nvim ~/Documents/Nvim/Vimwiki/Food\ Insecurity\ Study\ Notes.wiki' C-m
  # window: paper
  tmux new-window -c $proj"7.Writing/paper-spmirt"
  tmux rename-window "Paper"
  tmux send-keys "nvim 00-paper.tex" C-m
  # window: outline
  tmux new-window -c $proj"7.Writing/paper-spmirt"
  tmux rename-window "Outline"
  tmux send-keys "nvim outline_erick.Rmd" C-m
  # focus on window:
  tmux select-window -t "Paper"
  tmux attach-session -d
fi

